version: "3.8"
services:
  backend:
    container_name: backend
    image: node:lts
    volumes:
      - ./backend:/backend
    working_dir: /backend
    ports:
      - "4000:4000"
    command: yarn start:dev
    environment:
      NODE_ENV: development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/healthcheck"]
      interval: 1ms
      timeout: 5s
      retries: 3
      start_period: 20s
    depends_on: 
      - mongodb
  frontend:
    container_name: frontend
    image: node:lts
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - "3000:3000"
    command: yarn start
    environment:
      NODE_ENV: development
    depends_on: 
      - backend
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./.mongodb/db:/data/db
    ports:
      - 27017:27017
