version: '3.8'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/healthcheck']
      interval: 1ms
      timeout: 5s
      retries: 3
      start_period: 20s
    depends_on:
      - mongodb
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - '8080:80'
    environment:
      NODE_ENV: production
    depends_on:
      - backend
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./.mongodb/db:/data/db
    ports:
      - 27017:27017
